import React, { useState } from 'react';
import { Card, Field, MovementTable } from './components.jsx';
import { types, statuses } from './data.js';

export default function Console({ companies, accounts, movements, setAccounts, setMovements, onApp }) {
  const [companyId, setCompanyId] = useState(companies[0]?.id || '');
  const [chosen, setChosen] = useState('');
  const available = accounts.filter(a => a.companyId === companyId);
  const accountId = available.some(a => a.id === chosen) ? chosen : available[0]?.id || '';
  const [message, setMessage] = useState('Modo visual: nada se envía a Nessie. Los cambios se pierden al recargar.');
  const [type, setType] = useState('deposit');
  const [merchants, setMerchants] = useState(['Comercio de ejemplo']);
  const [confirmDelete, setConfirmDelete] = useState(null);
  function createMovement(e) {
    e.preventDefault(); const form = new FormData(e.currentTarget);
    const amount = Number(form.get('amount'));
    if (!accountId || !Number.isFinite(amount) || amount <= 0) return;
    setMovements(prev => [{ id: crypto.randomUUID(), accountId, type, amount, description: form.get('description').trim(), date: form.get('date'), status: form.get('status'), payee: form.get('payee'), merchant: form.get('merchant') }, ...prev]);
    setMessage('Movimiento de ejemplo creado. Puedes verlo en la app, sin salir de esta pestaña.');
  }
  return <main className="console"><header><div><p className="eyebrow">BUSYNESSY / LABORATORIO</p><h1>Consola de pruebas</h1></div><button onClick={onApp}>Abrir aplicación ↗</button></header><p>Explora la interfaz de cuentas y movimientos con datos locales.</p><p role="status" className="notice">{message}</p>
    <Card><h2>Cliente y cuenta</h2><div className="form-grid"><Field label="Cliente"><select value={companyId} onChange={e => { setCompanyId(e.target.value); setChosen(''); setConfirmDelete(null); }}>{companies.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Cuenta"><select value={accountId} onChange={e => { setChosen(e.target.value); setConfirmDelete(null); }}>{!available.length && <option value="">Sin cuentas</option>}{available.map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></Field></div><div className="button-row"><button className="subtle" onClick={() => setMessage('Vista local actualizada. No se realizó ninguna llamada al banco.')}>Actualizar vista</button><button className="danger" disabled={!accountId} onClick={() => setConfirmDelete(accountId)}>Eliminar cuenta de ejemplo</button></div>{confirmDelete && <div className="notice" role="alert"><p>¿Eliminar esta cuenta y sus movimientos locales de ejemplo?</p><button onClick={() => { setAccounts(prev => prev.filter(a => a.id !== confirmDelete)); setMovements(prev => prev.filter(m => m.accountId !== confirmDelete)); setConfirmDelete(null); setMessage('Cuenta local eliminada. Ningún dato bancario fue modificado.'); }}>Confirmar eliminación</button> <button className="subtle" onClick={() => setConfirmDelete(null)}>Cancelar</button></div>}<details><summary>Crear otra cuenta</summary><form onSubmit={e => { e.preventDefault(); const name = new FormData(e.currentTarget).get('nickname').trim(); if (!name) return; const id = crypto.randomUUID(); setAccounts(prev => [...prev, { id, companyId, name }]); setChosen(id); setMessage('Cuenta de ejemplo creada.'); e.currentTarget.reset(); }}><Field label="Nombre de la cuenta"><input name="nickname" required maxLength="100" /></Field><button disabled={!companyId}>Crear cuenta de ejemplo</button></form></details></Card>
    <Card><h2>Crear movimiento</h2><form onSubmit={createMovement}><div className="form-grid"><Field label="Tipo"><select value={type} onChange={e => setType(e.target.value)}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Monto (USD)"><input name="amount" type="number" min="0.01" step="0.01" defaultValue="250" required /></Field><Field label="Descripción"><input name="description" defaultValue="Prueba Busynessy" maxLength="250" required /></Field><Field label="Fecha"><input name="date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></Field><Field label="Estado"><select key={type} name="status" defaultValue={type === 'bill' ? 'pending' : 'completed'}>{Object.entries(statuses).filter(([value]) => type === 'bill' || value !== 'recurring').map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></Field>{type === 'purchase' && <Field label="Comercio"><select name="merchant" required>{merchants.map(m => <option key={m}>{m}</option>)}</select></Field>}{type === 'bill' && <Field label="Beneficiario"><input name="payee" required maxLength="120" /></Field>}</div><button disabled={!accountId}>Crear movimiento de ejemplo</button></form><p className="hint">Las facturas pendientes no cuentan como gastos pagados.</p></Card>
    <Card><details><summary>Crear comercio de prueba</summary><form onSubmit={e => { e.preventDefault(); const name = new FormData(e.currentTarget).get('merchant').trim(); if (!name) return; setMerchants(prev => [...new Set([...prev, name])]); setMessage('Comercio local agregado.'); e.currentTarget.reset(); }}><Field label="Nombre del comercio"><input name="merchant" required /></Field><button>Crear comercio de ejemplo</button></form></details></Card>
    <Card><h2>Historial completo</h2><p>Consulta de movimientos. Sin acciones de editar ni eliminar.</p><MovementTable movements={movements.filter(m => m.accountId === accountId)} /></Card><footer>Prototipo React · Solo interfaz y estado local.</footer></main>;
}
