const $=id=>document.getElementById(id), API="http://127.0.0.1:8787/api/";
let working=false, loading=false, revision=0;
const names={deposit:"Depósito",withdrawal:"Retiro",purchase:"Compra",bill:"Factura"};
async function request(route,method="GET",body){const r=await fetch(API+route,{method,...(body?{headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||"Error de API");return d;}
function options(el,list,label,selected){el.replaceChildren();list.forEach(x=>el.add(new Option(label(x),x._id)));if(list.some(x=>x._id===selected))el.value=selected;}
async function action(fn){if(working)return;working=true;document.querySelectorAll("button").forEach(b=>b.disabled=true);try{await fn();}catch(e){$("message").textContent=e.message;}finally{working=false;document.querySelectorAll("button").forEach(b=>b.disabled=false);}}
function fields(){const t=$("type").value;$("merchantField").hidden=t!=="purchase";$("payeeField").hidden=t!=="bill";$("merchant").required=t==="purchase";$("payee").required=t==="bill";$("status").querySelector('[value="recurring"]').disabled=t!=="bill";if(t!=="bill"&&$("status").value==="recurring")$("status").value="pending";}
async function accounts(){revision++;const list=await request("accounts/"+encodeURIComponent($("customer").value));options($("account"),list,x=>x.nickname+" · "+x.balance+" USD",$("account").value);await history();}
async function customers(){const list=await request("customers");options($("customer"),list,x=>x.first_name+" "+x.last_name,$("customer").value);if(list.length)await accounts();else{$("account").replaceChildren();await history();}}
async function history(){if(loading)return;const account=$("account").value,token=revision;if(!account){$("movements").replaceChildren();$("synced").textContent="Este cliente no tiene cuentas. Puedes crear una arriba.";return;}loading=true;try{const d=await request("movements/"+account);if(token!==revision||account!==$("account").value)return;$("accountInfo").textContent="ID cuenta: "+account;const list=Object.entries({deposits:"deposit",withdrawals:"withdrawal",purchases:"purchase",bills:"bill"}).flatMap(([key,type])=>(d[key]||[]).map(m=>({...m,type}))).sort((a,b)=>String(b.transaction_date||b.purchase_date||b.payment_date).localeCompare(String(a.transaction_date||a.purchase_date||a.payment_date)));$("movements").replaceChildren();for(const m of list){const tr=document.createElement("tr");for(const text of [names[m.type]+" · "+m._id,m.description||m.nickname||m.payee||"Sin descripción",m.transaction_date||m.purchase_date||m.payment_date,m.status,Number(m.amount??m.payment_amount).toFixed(2)]){const td=document.createElement("td");td.textContent=text;tr.append(td);}$("movements").append(tr);}$("synced").textContent=list.length+" registros · Actualizado "+new Date().toLocaleTimeString()+" · Consulta automática cada 3 segundos.";}finally{loading=false;}}
$("date").value=new Date().toISOString().slice(0,10);$("type").onchange=fields;
$("customer").onchange=()=>action(accounts);$("account").onchange=()=>action(async()=>{revision++;await history();});$("refresh").onclick=()=>action(customers);
$("accountForm").onsubmit=e=>{e.preventDefault();action(async()=>{if(!$("customer").value)throw Error("Selecciona cliente");const d=await request("accounts","POST",{customerId:$("customer").value,nickname:$("nickname").value,balance:0});await accounts();$("account").value=d.objectCreated._id;revision++;await history();$("message").textContent="Cuenta creada en Nessie.";});};
$("deleteAccount").onclick=()=>action(async()=>{const id=$("account").value;if(!id)throw Error("Selecciona cuenta");if(!confirm("¿Eliminar definitivamente la cuenta "+$("account").selectedOptions[0].textContent+" ("+id+")? Puede eliminar su historial. No se puede deshacer."))return;await request("accounts/"+id,"DELETE");await accounts();$("message").textContent="Cuenta eliminada de Nessie. No se puede deshacer.";});
$("movementForm").onsubmit=e=>{e.preventDefault();action(async()=>{const accountId=$("account").value;if(!accountId)throw Error("Selecciona cuenta");const body={accountId,type:$("type").value,amount:Number($("amount").value),description:$("description").value,date:$("date").value,status:$("status").value,merchantId:$("merchant").value,payee:$("payee").value};await request("movements","POST",body);$("message").textContent="Guardado en Nessie. La aplicación consulta la misma cuenta automáticamente.";await history();});};
$("merchantForm").onsubmit=e=>{e.preventDefault();action(async()=>{const d=await request("merchants","POST",{name:$("merchantName").value});options($("merchant"),await request("merchants"),x=>x.name,d.objectCreated._id);$("message").textContent="Comercio creado. Ya puedes registrar compras.";});};
action(async()=>{await customers();const list=await request("merchants");options($("merchant"),list,x=>x.name);$("message").textContent="Conectado a Nessie. Selecciona el mismo cliente y cuenta que en la aplicación."+(list.length?"":" Crea un comercio de prueba para habilitar compras.");});
fields();setInterval(()=>{if(!working)history().catch(e=>$("synced").textContent="Sin actualizar: "+e.message);},3000);
